# Generated by Django 5.0 on 2024-04-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_total_rating_book_total_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='highlights',
            field=models.TextField(default='', max_length=500),
        ),
    ]
