# Generated by Django 5.0 on 2024-04-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_highlights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='highlights',
            field=models.TextField(blank=True, default=None, max_length=500),
        ),
    ]
