# Generated by Django 5.0 on 2024-04-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
