# Generated by Django 5.0 on 2024-04-26 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_product_id_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cart',
            name='books',
            field=models.ManyToManyField(to='books.book'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
