# Generated by Django 5.0 on 2024-04-26 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='book',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
